name: 'V1-B$(Date:yyyyMMdd)-$(BuildID)'

parameters:
  - name: forceDevDeploy
    displayName: "Force deployment to DEV"
    type: boolean
    default: false
  - name: deployToSecondary
    displayName: "Select Secondary Region"
    type: string
    default: PRD
    values:
      - None
      - DEV
      - TST
      - PRE
      - PRD

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
      - webapps/sign-up-sign-in-service-ui/*

resources:
  repositories:
    - repository: trdPipelineCommon
      name: DEFRA-TRD/Defra.TRD.Pipeline.Common
      type: git
      ref: master

extends:
  template: /templates/defra-common-arm-deploy.yaml@trdPipelineCommon
  parameters:
    templates:
      - path: webapps/sign-up-sign-in-service-ui
        name: sign-up-sign-in-service-ui
        resourceGroupName: '$(Environment.Name)GC$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(nc-region-id)01'
        scope: 'Resource Group'
        type: 'bicep'
        runPrivateEndpointDns: true
        resourceName: '$(Environment.Name)GC$(nc-function-web)$(nc-resource-webapp)$(nc-region-id)01'
        postDeployScriptsList:
          - displayName: 'Assign App Roles to Managed Identity'
            scriptRepo: trdPipelineCommon
            scriptPath: '/templates/powershell/appregs/AssignAppRolesToApp.ps1'
            scriptArguments: '-AppName $(Environment.Name)GC$(nc-function-web)$(nc-resource-webapp)$(nc-region-id)01 -BackendAppName $(Environment.Name)TRA$(nc-function-infrastructure)$(nc-resource-apimanagement)1002-Backend-ApimOAuth -RolesToAssinToApp $(roleTradeRemosRead),$(roleTradeRemosUpdate) -Clientid $(AdoSpClientId) -ClientSecret $(AdoSpClientSecret) -TenantId $(TenantId)'
    forceDevDeploy: ${{ parameters.forceDevDeploy }}
    projectName: REM    
    deployToSecondary: ${{ parameters.deployToSecondary}}
    additionalVariablesFileList:
      - /vars/claims/jwt-claims-internal.yaml@trdPipelineCommon
    keyVaultName: '$(Environment.Name)trdinfkv1001'