name: 'V1-B$(Date:yyyyMMdd)-$(BuildID)'

parameters:
  - name: forceDevDeploy
    displayName: "Force deployment to DEV"
    type: boolean
    default: false
  - name: deployToSecondary
    displayName: "Select Secondary Region"
    type: string
    default: PRD
    values:
      - None
      - DEV
      - TST
      - PRE
      - PRD

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
      - appserviceplans/*

resources:
  repositories:
    - repository: trdPipelineCommon
      name: DEFRA-TRD/Defra.TRD.Pipeline.Common
      type: git
      ref: master

extends:
  template: /templates/defra-common-arm-deploy.yaml@trdPipelineCommon
  parameters:
    templates:
      - path: appserviceplans
        name: appserviceplans
        resourceGroupName: '$(Environment.Name)GC$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(nc-region-id)01'
        scope: 'Resource Group'
        type: 'bicep'
    forceDevDeploy: ${{ parameters.forceDevDeploy }}
    projectName: TRS    
    deployToSecondary: ${{ parameters.deployToSecondary}}
    additionalVariablesFileList:
      - vars/asp-{environment}.yaml@self